name = "Pincode Delivery Checker"
handle = "pincode-checker"
type = "theme"
uid = "a26e5fb7-fc92-68a4-09d3-8c47854aebad778e04b1"

[settings]
  locales_path = "./locales"

[[targeting]]
  target = "section"
