# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c050fc533a8b10fec7132e44bea5d3b6"
application_url = "https://example.com"
embedded = true
name = "pincode-delivery-checker"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  # GDPR Mandatory Webhooks
  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [ "shop/redact", "customers/redact", "customers/data_request" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
